---
title: "writing_functions"
author: "Kailey Rishovd"
date: "11/15/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6, 
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot.continuous.colour = "viridis", 
  ggplot.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)
## vector that is normal, 30 values, mean 5, sd 3

(x_vec - mean(x_vec)) / sd(x_vec)
## gives you z scores that you can look at and scan for sd 
```

I want a function to compute z-scores 

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)){
    stop("Input must be numeric")
  }
  
  if (length(x)  < 3) {
    stop("Input must have at least 3 numbers")
  }
  
  z = (x - mean(x) / sd(x))
  
  return(z)
}

z_scores(x_vec)
```

Try my fucntion on some other things --- these should give errors... 

```{r, error=TRUE}
z_scores(3)
## doesnt work because sd will not return 

z_scores("my name is kailey")
## cannot take mean of character 

z_scores(mtcars)
## cant take the mean of a dataset 

z_scores(c(TRUE, TRUE, FALSE, TRUE))
## works becasue it turns logical into a sequence of 0 and 1s (coercion)

## in each of these, the function does something wrong
```

update the function (done in the function step above with adding if statements)

## Multiple outputs 

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Input must be numeric")
  }
  
  if (length(x)  < 3) {
    stop("Input must have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
## tibble makes it a dataframe 
```

Check that the function works 

```{r}
x_vec = rnorm(100, mean = 3, sd = 4)
## can do it this way or can make a function!! 

mean_and_sd(x_vec)
```

## Multiple inputs 

```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarize(
    mean = mean(x), 
    sd = sd(x)
  )

```
 I'd like to do this with a function..... 
 
```{r}
sim_mean_sd = function(samp_size, mu, sigma) {
  
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma)
    )

sim_data %>% 
  summarize(
    mean = mean(x), 
    sd = sd(x)
  )
}

sim_mean_sd(100, 6, 3)
## n = 100, mean = 6, sd = 3
## try to use named matching instead of purely position matching
## you can also set default values in the function; which can be overwritten with named matching 
```
 







